# Generated by Django 5.0.6 on 2024-06-13 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
