# Generated by Django 5.0.6 on 2024-08-12 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
