# Generated by Django 5.0.6 on 2024-09-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepicture',
            name='owner',
        ),
        migrations.DeleteModel(
            name='GalleryPicture',
        ),
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
