# Generated by Django 5.0.6 on 2024-07-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_myuser'),
    ]

    operations = [
        migrations.RenameModel('User', 'MyUser')
    ]
